In [1]:
import numpy as np

In [25]:
collection_data = []
collection_ppl = []

with open('../hw1/MLDS_HW1_RELEASE_v1/fbank/train.ark') as f:
    
#     count = 0
    for lines in f :
        frames = lines.split(' ')
#         print frames
#         break
        frame2float = np.array([ float(x) for x in frames[1:] ])
        
        collection_data.append(frame2float)
        collection_ppl.append(frames[0])


In [5]:
collection_data = np.array(collection_data)
collection_ppl = np.array(collection_ppl)

In [7]:
collection_ppl.shape

(1124823,)

In [8]:
from sklearn import preprocessing

collection_data

array([[  3.14854100e+00,   3.60388000e+00,   4.16070600e+00, ...,
         -3.33977000e-02,  -4.41806000e-02,  -6.92883100e-02],
       [  4.67721300e+00,   4.40031900e+00,   4.79517600e+00, ...,
         -1.01014200e-01,  -5.81350900e-03,  -7.69349000e-02],
       [  3.73649200e+00,   2.94018000e+00,   3.05038400e+00, ...,
         -1.29172800e-02,   8.44857400e-02,   2.53251500e-02],
       ..., 
       [  2.22448800e+00,   4.62495500e+00,   5.45315100e+00, ...,
          1.50332700e-01,   6.56526700e-02,   4.91675100e-02],
       [  1.81102300e+00,   3.54327000e+00,   5.01433100e+00, ...,
          6.41931900e-02,   5.94250600e-02,   5.56514300e-02],
       [  2.98250600e+00,   4.87457500e+00,   5.27762300e+00, ...,
         -2.21711400e-03,   1.84245700e-02,   2.89064600e-02]])

In [26]:
X_scaled = preprocessing.scale(collection_data)

X_scaled

array([[-1.76957371, -1.86505013, -1.88914171, ..., -0.11861642,
        -0.1632276 , -0.26120626],
       [-1.32482692, -1.66606706, -1.73784003, ..., -0.35876651,
        -0.0214528 , -0.29003616],
       [-1.59851718, -2.03086956, -2.15391953, ..., -0.04587715,
         0.3122227 ,  0.09551441],
       ..., 
       [-2.03841464, -1.60994379, -1.58093313, ...,  0.53392952,
         0.24263038,  0.18540715],
       [-2.15870678, -1.88019299, -1.68557827, ...,  0.22799219,
         0.219618  ,  0.20985344],
       [-1.81787938, -1.5475785 , -1.62279118, ..., -0.00787392,
         0.06811221,  0.10901701]])

In [11]:
collection_data[0]

array([  3.14854100e+00,   3.60388000e+00,   4.16070600e+00,
         3.52652900e+00,   4.07707600e+00,   6.67795900e+00,
         7.67193600e+00,   7.83670500e+00,   7.32835600e+00,
         7.56157300e+00,   8.23674500e+00,   7.38677800e+00,
         8.36810100e+00,   9.17519400e+00,   1.04442100e+01,
         9.68379800e+00,   1.08044200e+01,   1.10426800e+01,
         1.00662200e+01,   1.05513200e+01,   1.02885200e+01,
         1.10653600e+01,   1.15893900e+01,   2.70457400e-01,
        -5.30961200e-02,  -1.58617400e-01,   6.15164000e-02,
         2.80102700e-01,  -2.26393800e-01,  -4.12236000e-01,
        -5.60548900e-01,  -3.17220600e-01,  -2.38418600e-07,
        -1.19209300e-07,   1.86059400e-01,  -1.07679700e-01,
        -2.49691500e-01,  -4.65970600e-01,  -2.50453500e-01,
        -4.38481800e-01,  -2.64075000e-01,   5.48541500e-03,
        -2.38418600e-07,   1.43248100e-01,  -1.66646000e-01,
        -1.19460800e-01,  -1.25821500e-01,  -9.69001500e-02,
        -2.07788900e-01,

In [18]:
X_scaled[30]

array([ 0.26837359, -0.10361656, -0.07009379,  0.0601018 , -0.15001043,
        0.16226109,  0.09048964, -0.06705656, -0.10256069, -0.16583105,
       -0.01966666,  0.09105977,  0.13569611,  0.12026849,  0.18182775,
        0.34810207,  0.67375964,  1.25545696,  1.60132127,  2.08327632,
        2.67941819,  2.96118832,  2.61302385, -0.41551356,  0.19890471,
        0.04623837,  0.03506021,  0.10552128,  0.06425633,  0.42320458,
        0.04231888,  0.29043023,  0.06954323, -0.11847618,  0.29156701,
       -0.15069435,  0.05803577,  0.11025741, -0.09423197, -0.41861085,
       -0.24170476, -0.23599886, -0.11001958, -0.47152445, -0.88663275,
       -0.85352303, -0.15793202,  0.43675492,  0.59864497,  0.10028278,
        0.02366456, -0.16264229,  0.00315569, -0.02164825,  0.07080189,
        0.24188249,  0.48607523,  0.48880483,  0.18227654, -0.1004825 ,
        0.20185911, -0.12154577, -0.24843266, -0.31856876, -0.48114432,
       -0.41488321, -0.81527669, -1.13199797, -0.99709961])

In [27]:
print X_scaled.mean(axis=0)
print X_scaled.std(axis=0)

[ -1.12458593e-13   6.38598646e-14  -5.52192139e-14  -1.21234593e-13
  -1.51947970e-14   1.24229850e-13  -1.13828960e-13   5.32264535e-14
  -6.33351419e-14  -4.02948206e-14   1.80539430e-13  -1.75125873e-13
   2.55576589e-13  -2.06272760e-13   8.30189779e-14   1.45545545e-13
   2.63940511e-13  -1.92642722e-13   2.86514352e-13  -3.45366259e-13
   1.79310002e-13  -4.27086488e-14   1.44738947e-13   1.29171383e-16
  -1.76582602e-17  -1.24405661e-17   2.07345801e-17  -3.09786161e-18
   1.78572929e-17   7.28080387e-17   8.61796949e-18   9.19922569e-18
   6.37901286e-17   2.38062364e-17   7.28951432e-18  -6.26101460e-18
   3.17173698e-18   6.14239328e-18  -1.35141819e-17  -4.05517250e-18
  -2.68215954e-18  -2.76116187e-17  -9.46427577e-17   4.70289217e-18
  -1.84099502e-17  -9.92609204e-19   1.15449039e-17   1.37359407e-17
   2.30657738e-17  -1.42632161e-17  -5.69941244e-18   7.17208360e-18
   1.36298607e-17  -1.10950447e-17   6.26984843e-18  -1.14535552e-17
  -6.50463586e-18  -1.93477674e-17

# Write file

In [32]:
f = open("hwb_normalize.dat", 'w+')
# f.write("id,feature\n")
for ppl, data in zip(collection_ppl, X_scaled):
    f.write("{0} ".format(ppl))
    # for ddd in data:
    for i in range (len(data)):
        if( (i+1)!= len(data)):
            f.write("{0} ".format(data[i]))
        else:
            f.write("{0}\n".format(data[i]))
#     f.write("\n")
#     break
f.close()


In [31]:
collection_gg = []
collection_qq = []

with open('./hwb_normalize.dat') as f:
    
#     count = 0
    for lines in f :
        frames = lines.split(' ')
        print frames
        frame2float = np.array([ float(x) for x in frames[1:] ])
        
        collection_gg.append(frame2float)
        collection_qq.append(frames[0])


['faem0_si1392_1', '-1.76957370612', '-1.86505012596', '-1.88914171159', '-2.08833441533', '-2.04425496544', '-1.54067142305', '-1.40191900138', '-1.41618727831', '-1.57809341606', '-1.58456590498', '-1.49451958185', '-1.8009265165', '-1.62139990946', '-1.48169651677', '-1.16173764906', '-1.42343809869', '-1.16688646896', '-1.13558650877', '-1.39462615593', '-1.16493038495', '-1.20985099461', '-1.00835284404', '-0.881854735508', '0.385293665433', '-0.0688966743788', '-0.185577323357', '0.0609993442667', '0.276968649222', '-0.235241332044', '-0.458563906138', '-0.661452996468', '-0.382600570279', '-0.00127793281969', '-0.000414812879145', '0.221818844631', '-0.135264385803', '-0.317511993589', '-0.594179526972', '-0.316162012956', '-0.547867096256', '-0.340538809321', '0.00603289680086', '-0.00119396642394', '0.204789685053', '-0.249709742064', '-0.183023773178', '-0.462955254346', '-0.312252776059', '-0.620981484555', '-0.185196895126', '0.0430073189451', '-0.162560040815', '-0.4183652